name: Deploy glappy-landing to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Prepare site artifact
        run: |
          # make a clean output folder
          mkdir _site
          # copy everything from the repository root folder into it, excluding _site itself
          rsync -av --exclude '_site' ./ _site/
          # if you have a .git folder inside, remove it
          rm -rf _site/.github

      - name: Upload site artifact
        id: upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deploy
        uses: actions/deploy-pages@v4
