name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: glappy-artifact
          path: glappy-landing

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: glappy-artifact

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
